# Generated by Django 3.2.16 on 2022-10-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SS_author_ID', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorPosition', models.CharField(choices=[('F', 'First'), ('I', 'Intermediate'), ('L', 'Last')], max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citation_networks.author')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSID_paper_ID', models.CharField(max_length=1000, null=True, unique=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('journal_name', models.CharField(max_length=1000, null=True)),
                ('volume', models.CharField(max_length=100, null=True)),
                ('issue', models.CharField(max_length=100, null=True)),
                ('pages', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('citations_last_queried', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(through='citation_networks.Authorship', to='citation_networks.Author')),
                ('cited_by', models.ManyToManyField(blank=True, related_name='cites', to='citation_networks.Paper')),
                ('references', models.ManyToManyField(blank=True, related_name='refs', to='citation_networks.Paper')),
            ],
        ),
        migrations.AddField(
            model_name='authorship',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citation_networks.paper'),
        ),
    ]
